title: 文浩的技术博客
description: 记录技术学习、经验分享和个人成长
author: 文浩
url: https://wenhao-in-chengdu.github.io

# 主题设置
theme: minima

# 分页设置
paginate: 10
paginate_path: "/page:num/"

# Markdown渲染引擎
markdown: kramdown

# 永久链接格式
permalink: /:year/:month/:day/:title/

# 社交链接
social_links:
  github: wenhao-in-chengdu

# 默认布局
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "文浩" 